name: Pack Chrome Extension

on:
  release:
    types: [created]

jobs:
  pack-extension:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Chrome
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      # Create a temporary PEM file if not exists
      - name: Create or use PEM
        run: |
          if [ ! -f "./extension.pem" ]; then
            openssl genpkey -algorithm RSA -out extension.pem -pkeyopt rsa_keygen_bits:2048
          fi

      # Pack the extension using Chrome
      - name: Pack Extension
        run: |
          chromium-browser --pack-extension="$(pwd)" --pack-extension-key="$(pwd)/extension.pem"
          mv "$(pwd).crx" "${{ github.event.repository.name }}.crx"
      
      # Upload both CRX and PEM files to release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}.crx
            extension.pem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
