name: Pack Chrome Extension

on:
  release:
    types: [created]

jobs:
  pack-extension:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Pack Chrome Extension
        uses: emilymclean/pack-chromium-extension@v1
        with:
          input-folder: '.'  # Root directory containing your extension source
          output-file: '${{ github.event.repository.name }}.crx'  # Will use repo name as the file name
      
      - name: Upload Extension to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.event.repository.name }}.crx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
